#! /bin/sh

sxhkd &

bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 todo web
bspc monitor VGA-1 -d 1 2 3 4 5
bspc monitor VGA-2 -d 6 7 8 todo web
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 todo web

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config -m HDMI-0 bottom_padding 360
bspc config -m HDMI-0 top_padding 300

bspc config -m VGA-2 bottom_padding 360
bspc config -m VGA-2 top_padding 300

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a '*:zathura' state=tiled

feh --bg-fill $(find ~/.config/backgrounds -type f | shuf -n 1)

.config/polybar/launch

pkill conky
conky -d -c .config/conky/sys.conf
conky -d -c .config/conky/todo.conf
conky -d -c .config/conky/docs.conf
conky -d -c .config/conky/undocs.conf

pkill greenclip
/usr/bin/greenclip daemon
